# Project info
site_name: Metrixcoin Documentation
site_description: The official documentation for the Metrixcoin blockchain and products
site_author: The Metrixcoin Developers
site_url: https://docs.metrixcoin.com

# Copyright
copyright: Copyright &copy; 2023 The Metrixcoin Developers

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
      text: Roboto
      code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking # insiders
    - navigation.tabs
    - navigation.tabs.sticky # insiders
    - navigation.indexes # insiders
    - navigation.top

plugins:
  - search

extra:
  homepage: https://metrixcoin.com
  social:
    - icon: fontawesome/solid/globe
      link: https://metrixcoin.com
    - icon: fontawesome/brands/discord
      link: https://discord.gg/sFDhZk4Nxb
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/officialmetrixcoinnews
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/metrixcoin
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/MetrixCoin/
    - icon: fontawesome/brands/telegram
      link: https://t.me/officialmetrixcoin

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: '#'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


nav:
  - Home:
    - Home: index.md
    - Altitude:
      - Installation: altitude/install.md
      - First Run: altitude/firstrun.md
      - Basic Functions: altitude/basicfunctions.md
      - Governor: altitude/governor.md
      - Backup: altitude/backup.md
      - Staking: altitude/staking.md
      - Troubleshooting: altitude/troubleshooting.md
    - Core:
      - Install: core/install.md
      - Starting: core/starting.md
      - Command Glossary: core/commands.md
      - Exchange Usage Guide: core/exchange-usage-guide.md
    - DGP:
      - About the DGP: dgp/about.md
      - Command Glossary: dgp/commands.md
      - Migration to DGPv2: dgp/v2migration.md
      - Migration to DGPv3: dgp/v3migration.md
    - MRC20:
      - About: mrc20/about.md
      - MRC Integration Technical Guide: mrc20/integration.md
    - Docker:
      - About: docker/about.md
    - MyStakingWallet:
      - Recover Deleted Wallets: mystakingwallet/recover-deleted-wallets.md
      - Billing: mystakingwallet/billing.md
    - TroubleShooting:
      - MacOS Manual Core Install: troubleshooting/macos-manual-core.md
    - Links: links/links.md
    - FAQ: faq.md
  - Developers:
    - Developers: developers/index.md
